/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIndexRouteImport } from './routes/songs.index'
import { Route as UnitUnitSlugRouteImport } from './routes/unit.$unitSlug'
import { Route as SongsImportRouteImport } from './routes/songs.import'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitUnitSlugRoute = UnitUnitSlugRouteImport.update({
  id: '/unit/$unitSlug',
  path: '/unit/$unitSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsImportRoute = SongsImportRouteImport.update({
  id: '/songs/import',
  path: '/songs/import',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/songs/import': typeof SongsImportRoute
  '/unit/$unitSlug': typeof UnitUnitSlugRoute
  '/songs/': typeof SongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/songs/import': typeof SongsImportRoute
  '/unit/$unitSlug': typeof UnitUnitSlugRoute
  '/songs': typeof SongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/songs/import': typeof SongsImportRoute
  '/unit/$unitSlug': typeof UnitUnitSlugRoute
  '/songs/': typeof SongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/journey'
    | '/practice'
    | '/profile'
    | '/lesson/$lessonId'
    | '/songs/$songId'
    | '/songs/import'
    | '/unit/$unitSlug'
    | '/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/journey'
    | '/practice'
    | '/profile'
    | '/lesson/$lessonId'
    | '/songs/$songId'
    | '/songs/import'
    | '/unit/$unitSlug'
    | '/songs'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/journey'
    | '/practice'
    | '/profile'
    | '/lesson/$lessonId'
    | '/songs/$songId'
    | '/songs/import'
    | '/unit/$unitSlug'
    | '/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  JourneyRoute: typeof JourneyRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  SongsSongIdRoute: typeof SongsSongIdRoute
  SongsImportRoute: typeof SongsImportRoute
  UnitUnitSlugRoute: typeof UnitUnitSlugRoute
  SongsIndexRoute: typeof SongsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/$unitSlug': {
      id: '/unit/$unitSlug'
      path: '/unit/$unitSlug'
      fullPath: '/unit/$unitSlug'
      preLoaderRoute: typeof UnitUnitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/import': {
      id: '/songs/import'
      path: '/songs/import'
      fullPath: '/songs/import'
      preLoaderRoute: typeof SongsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  JourneyRoute: JourneyRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  SongsSongIdRoute: SongsSongIdRoute,
  SongsImportRoute: SongsImportRoute,
  UnitUnitSlugRoute: UnitUnitSlugRoute,
  SongsIndexRoute: SongsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
